apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-1-httpd
  template:
    metadata:
      labels:
        app: workload-1-httpd
    spec:
      containers:
        - name: httpd
          image: ubi8/httpd-24:latest
