apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-1
  template:
    metadata:
      labels:
        app: httpd-1
    spec:
      containers:
        - name: httpd
          image: ubi8/httpd-24:latest
