apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-2
  template:
    metadata:
      labels:
        app: httpd-2
    spec:
      containers:
        - name: httpd
          image: ubi8/httpd-24:latest
          ports:
            - containerPort: 8080
