apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-2
  template:
    metadata:
      labels:
        app: httpd-2
    spec:
      containers:
        - name: httpd
          image: registry.redhat.io/ubi8/httpd-24:1-191
          ports:
            - containerPort: 8080
